import { Project, CareerMilestone } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'SABRINA KISS',
    client: 'Self-Directed',
    year: '2025',
    thumbnail: '/photos/SABRINA_KISS.png',
    videoUrl: '/videos/sabrina.mov',
    duration: '00:14',
    tags: ['Color Grade', 'VFX', 'Sound'],
    description: 'A visual exploration of a futuristic cityscape using advanced color grading and custom sound design.',
    idealGrade: 'CINEMA',
    aspectRatio: '16:9',
    spherePosition: [8, 0, 0]
  },
  {
    id: 'p2',
    title: 'TEXTURE MOTION EDIT',
    client: 'NIMBUS',
    year: '2023',
    thumbnail: '/photos/TEXTURE_MOTION_EDIT.png',
    videoUrl: '/videos/khtmsdfgh_1_41.mp4',
    duration: '01:41',
    tags: ['Rhythm Edit', 'Motion'],
    description: 'High-energy rhythmic editing showcase for a lifestyle brand campaign.',
    idealGrade: 'BLEACH',
    aspectRatio: '16:9',
    spherePosition: [5.66, 5.66, 0]
    //public/videos/
  },
  {
    id: 'p3',
    title: 'MASKING_EDIT_REEL',
    client: 'Self_Project',
    year: '2023',
    thumbnail: '/photos/MASKING_EDIT_REEL.png',
    videoUrl: '/videos/triund_16.mov',
    duration: '00:16',
    tags: ['Nature', 'Storytelling'],
    description: 'Documentary style narrative focused on the ecosystem of the Redwood forests.',
    idealGrade: 'REC709',
    aspectRatio: '16:9',
    spherePosition: [0, 8, 0]
  },
  {
    id: 'p4',
    title: 'SHORT FILM',
    client: 'NIMBUS',
    year: '2024',
    thumbnail: '/photos/SHORT_FILM.png',
    videoUrl: '/videos/super_final_koladeio_1_12.mp4',
    duration: '01:12',
    tags: ['Music Video', 'Stylistic'],
    description: 'Experimental music video featuring heavy glitch effects and fast-paced intercutting.',
    idealGrade: 'MONO',
    aspectRatio: '16:9',
    spherePosition: [-5.66, 5.66, 0]
  },
  {
    id: 'p5',
    title: 'PRODUCT ANIMATION',
    client: 'RTX',
    year: '2023',
    thumbnail: '/photos/PRODUCT_ANIMATION.png',
    videoUrl: '/videos/rtxfinal_36.mp4',
    duration: '00:36',
    tags: ['Travel', 'Cinematic'],
    description: 'A sweeping cinematic journey through the dunes of the Sahara.',
    idealGrade: 'CINEMA',
    aspectRatio: '9:16',
    spherePosition: [-8, 0, 0]
  },
  {
    id: 'p6',
    title: 'TMOTION EDIT',
    client: 'NIMBUS',
    year: '2025',
    thumbnail: '/photos/MOTION_EDIT.png',
    videoUrl: '/videos/nimbuuexportvjbjk_20.mp4',
    duration: '00:20',
    tags: ['Corporate', 'Minimal'],
    description: 'Clean, professional corporate overview for a manufacturing giant.',
    idealGrade: 'REC709',
    aspectRatio: '16:9',
    spherePosition: [-5.66, -5.66, 0]
  },
  {
    id: 'p7',
    title: 'LOGO ANIMATION',
    client: 'VIBHAV',
    year: '2024',
    thumbnail: '/photos/LOGO_ANIMATION_1.png',
    videoUrl: '/videos/vibhav_Comp_4.mp4',
    duration: '00:04',
    tags: ['Music', 'Abstract'],
    description: 'Abstract visuals paired with deep house rhythms.',
    idealGrade: 'LOG',
    aspectRatio: '16:9',
    spherePosition: [0, -8, 0]
  },
  {
    id: 'p8',
    title: 'PROMOTIONAL EDIT',
    client: 'VIBHAV',
    year: '2023',
    thumbnail: '/photos/PROMOTIONAL_EDIT_1.png',
    videoUrl: '/videos/team_37.mp4',
    duration: '00:37',
    tags: ['Scientific', 'Slow'],
    description: 'Underwater exploration of bioluminescent species.',
    idealGrade: 'CINEMA',
    aspectRatio: '9:16',
    spherePosition: [5.66, -5.66, 0]
  },
  {
    id: 'p9',
    title: 'Echoes of the Past',
    client: 'Museum of History',
    year: '2024',
    thumbnail: 'https://picsum.photos/seed/history/1280/720',
    videoUrl: '/videos/sabrina_14.mov',
    duration: '00:14',
    tags: ['Documentary', 'Vintage'],
    description: 'A retrospective look at historical milestones through archived footage.',
    idealGrade: 'MONO',
    aspectRatio: '16:9',
    spherePosition: [0, 0, 8]
  },
  {
    id: 'p10',
    title: 'MASKING EDIT PRE NIMBUS',
    client: 'NIMBUS',
    year: '2025',
    thumbnail: '/photos/MASKING_EDIT_prenimbus.png',
    videoUrl: '/videos/pre_46.mp4',
    duration: '00:46',
    tags: ['Action', 'High-Speed'],
    description: 'Intense trackside footage captured at 240fps.',
    idealGrade: 'BLEACH',
    aspectRatio: '9:16',
    spherePosition: [0, 0, -8]
  },
  {
    id: 'p11',
    title: 'Aurora Borealis',
    client: 'Arctic Expeditions',
    year: '2023',
    thumbnail: 'https://picsum.photos/seed/aurora/1280/720',
    videoUrl: '/videos/nim_40.mp4',
    duration: '00:04',
    tags: ['Time-lapse', 'Nature'],
    description: 'Breathtaking 8K time-lapse of the Northern Lights.',
    idealGrade: 'CINEMA',
    aspectRatio: '16:9',
    spherePosition: [4, 4, 5.66]
  },
  {
    id: 'p12',
    title: 'ORIENTATION REEL',
    client: 'VIBHAV',
    year: '2024',
    thumbnail: '/photos/ORIENTATION_REEL.png',
    videoUrl: '/videos/ori_1_4.mp4',
    duration: '01:04',
    tags: ['Tech', 'Dataviz'],
    description: 'Visualizing global data flows in a sleek, modern aesthetic.',
    idealGrade: 'REC709',
    aspectRatio: '16:9',
    spherePosition: [-4, 4, 5.66]
  },
  {
    id: 'p13',
    title: 'The Maker Space',
    client: 'Artisans Guild',
    year: '2024',
    thumbnail: 'https://picsum.photos/seed/craft/1280/720',
    videoUrl: '/videos/logo_3.mp4',
    duration: '00:03',
    tags: ['Craft', 'Makers'],
    description: 'Showcasing the meticulous process of hand-crafted tool making.',
    idealGrade: 'LOG',
    aspectRatio: '16:9',
    spherePosition: [-4, -4, 5.66]
  },
  {
    id: 'p14',
    title: 'HOODIE MOCKUP',
    client: 'TEDX',
    year: '2025',
    thumbnail: '/photos/HOODIE_MOCKUP.png',
    videoUrl: '/videos/VID-20260205-WA0004_13-1.mp4',
    duration: '00:13',
    tags: ['Documentary', 'Space'],
    description: 'A deep dive into the future of lunar colonization.',
    idealGrade: 'CINEMA',
    aspectRatio: '1:1',
    spherePosition: [4, -4, 5.66]
  },
  {
    id: 'p15',
    title: 'TEXTURE MOTION EDIT',
    client: 'NIMBUS',
    year: '2023',
    thumbnail: '/photos/TEXTURE_MOTION_EDIT.png',
    videoUrl: '/videos/khtmsdfgh_1_41.mp4',
    duration: '01:41',
    tags: ['Urban', 'Architecture'],
    description: 'Rhythmic study of urban movement and infrastructure.',
    idealGrade: 'BLEACH',
    aspectRatio: '16:9',
    spherePosition: [4, 4, -5.66]
  },
  {
    id: 'p16',
    title: 'LINEART ANIMATION',
    client: 'NIMBUS',
    year: '2024',
    thumbnail: '/photos/LINEART_ANIMATION.png',
    videoUrl: '/videos/intro_7.mp4',
    duration: '00:07',
    tags: ['Reels', 'Vertical'],
    description: 'A collection of the best golden hour moments across Europe.',
    idealGrade: 'CINEMA',
    aspectRatio: '16:9',
    spherePosition: [-4, 4, -5.66]
  },
  {
    id: 'p17',
    title: 'EVENT_PROMOTION_REEL',
    client: 'VIBHAV',
    year: '2023',
    thumbnail: '/photos/EVENT_PROMOTION_REEL.png',
    videoUrl: '/videos/IMG_6930_1_18.mp4',
    duration: '01:18',
    tags: ['Adventure', 'Climbing'],
    description: 'Documentation of a solo ascent in the Himalayas.',
    idealGrade: 'LOG',
    aspectRatio: '9:16',
    spherePosition: [-4, -4, -5.66]
  },
  {
    id: 'p18',
    title: 'PROMOTIONAL REEL',
    client: 'VIBHAV',
    year: '2025',
    thumbnail: '/photos/PROMOTIONAL_REEL_2.png',
    videoUrl: '/videos/final_v_day.mp4',
    duration: '00:37',
    tags: ['Innovation', 'Abstract'],
    description: 'Visualizing the birth of an idea in the digital age.',
    idealGrade: 'MONO',
    aspectRatio: '9:16',
    spherePosition: [4, -4, -5.66]
  },
  {
    id: 'p19',
    title: 'Zen Garden',
    client: 'Lifestyle Brand',
    year: '2024',
    thumbnail: 'https://picsum.photos/seed/zen/1280/720',
    videoUrl: '/videos/final_53.mp4',
    duration: '00:53',
    tags: ['Ambient', 'Relaxation'],
    description: '20 minutes of meditative garden visuals for focused work.',
    idealGrade: 'REC709',
    aspectRatio: '9:16',
    spherePosition: [5.66, 0, 5.66]
  },
  {
    id: 'p20',
    title: 'Electric Symphony',
    client: 'Audio Visualizer',
    year: '2024',
    thumbnail: 'https://picsum.photos/seed/music/1280/720',
    videoUrl: '/videos/compiled.mp4',
    duration: '00:24',
    tags: ['Music', 'Visuals'],
    description: 'Reactive visuals that dance to a complex synth score.',
    idealGrade: 'CINEMA',
    aspectRatio: '9:16',
    spherePosition: [-5.66, 0, 5.66]
  },
  {
    id: 'p21',
    title: 'MATCHCUT EDIT',
    client: 'TragoMedia',
    year: '2023',
    thumbnail: '/photos/MATCHCUT_EDIT.png',
    videoUrl: '/videos/comment_almost_intro.mp4',
    duration: '00:07',
    tags: ['Wildlife', 'Epic'],
    description: 'Footage of more than a million wildebeest moving across the Serengeti.',
    idealGrade: 'CINEMA',
    aspectRatio: '16:9',
    spherePosition: [-5.66, 0, -5.66]
  },
  {
    id: 'p22',
    title: 'WEEDING MOTION ANIMATION',
    client: 'Streetwear Label',
    year: '2025',
    thumbnail: '/photos/WEEDING_MOTION_ANIMATION.png',
    videoUrl: '/videos/weeding_51.mp4',
    duration: '00:51',
    tags: ['Fashion', 'Edgy'],
    description: 'High-contrast fashion film shot in the tunnels of Tokyo.',
    idealGrade: 'BLEACH',
    aspectRatio: '16:9',
    spherePosition: [5.66, 0, -5.66]
  },
  {
    id: 'p23',
    title: 'Crystal Clear',
    client: 'Luxury Jewelry',
    year: '2024',
    thumbnail: 'https://picsum.photos/seed/diamond/1280/720',
    videoUrl: '/videos/comment_almost_intro.mp4',
    duration: '00:30',
    tags: ['Macro', 'Product'],
    description: 'Ultra-macro study of light refraction in high-end diamonds.',
    idealGrade: 'REC709',
    aspectRatio: '1:1',
    spherePosition: [0, 5.66, 5.66]
  },
  {
    id: 'p24',
    title: 'Endless Summer',
    client: 'Surf Brand',
    year: '2023',
    thumbnail: 'https://picsum.photos/seed/surf/1280/720',
    duration: '05:50',
    tags: ['Sports', 'Vibrant'],
    description: 'Chasing the perfect wave across the coast of Australia.',
    idealGrade: 'CINEMA',
    aspectRatio: '16:9',
    spherePosition: [0, -5.66, -5.66]
  }
];

export const MILESTONES: CareerMilestone[] = [
  { id: 'm1', year: '2018', event: 'Started Editing', type: 'education', color: '#4a90e2', timestamp: 10 },
  { id: 'm2', year: '2020', event: 'First Commercial', type: 'project', color: '#50e3c2', timestamp: 30 },
  { id: 'm3', year: '2021', event: 'Adobe Certified', type: 'education', color: '#f5a623', timestamp: 45 },
  { id: 'm4', year: '2022', event: 'VFX Course', type: 'education', color: '#d0021b', timestamp: 65 },
  { id: 'm5', year: '2023', event: 'Best Short Edit', type: 'award', color: '#bd10e0', timestamp: 85 },
];
